
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ucbl_pidji:
    resource: "@UCBLPidjiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

